export const mockFestivals = [
  {
    id: 1,
    title: '제5회 강릉 비치비어페스티벌',
    location: '경포해변 중앙광장',
    startDate: '2025.06.27',
    endDate: '2025.06.29',
    region: '강원',
    category: '관광형',
    reviews: 3,
    price: 0,
    thumbnail: '/images/test/festival1.jpg',
  },
  {
    id: 2,
    title: '서울 불꽃놀이 축제',
    location: '한강 반포지구',
    startDate: '2025.10.05',
    endDate: '2025.10.05',
    region: '서울',
    category: '야간형',
    reviews: 12,
    price: 0,
    thumbnail: '/images/test/festival2.jpg',
  },
  {
    id: 3,
    title: '제주 푸드트럭 페스타',
    location: '제주시 탑동광장',
    startDate: '2025.08.15',
    endDate: '2025.08.17',
    region: '제주도',
    category: '푸드형',
    reviews: 5,
    price: 2000,
    thumbnail: '/images/test/festival3.jpg',
  },
  {
    id: 4,
    title: 'DMZ 평화 음악제',
    location: '철원 평화공원',
    startDate: '2025.09.01',
    endDate: '2025.09.03',
    region: '경기도',
    category: '음악형',
    reviews: 8,
    price: 0,
    thumbnail: '/images/test/festival4.jpg',
  },
];
