export const mockDiaries = [
  {
    id: 1,
    authorName: '박수연',
    authorImage: '/mock/user1.png',
    date: '2025.08.01',
    likes: 10,
    content:
      '해질 무렵 바다를 배경으로 펼쳐진 비치비어 페스티벌은 탁 트인 풍경이 시원한 분위기를 더해줬다! 개성 있는 수제 맥주 라인업 덕분에 평소에 접하기 힘든 다양한 맛을 시도해볼 수 있어 너무너무 만족스러웠다... 라이브 음악과 퍼포먼스가 중간중간 분위기를 끌어올려서 친구들이랑 같이 갔으면 더 즐거웠을 듯 ㅜㅜ (나는 혼자서 감...)\n \n 음식 부스도 다양해서 맥주와 잘 어울리는 피자, 타코, 통닭 등 안주를 골라 먹는 재미가 있었음 🌮 주차와 입장 대기 줄이 긴 편이었지만, 그런 시간마저도 마치 여행의 일부처럼 느껴져 전체적으로 즐거운 경험이어따...',
    images: ['/images/test/review1.png', '/images/test/review2.png'],
    isPublic: true,
    festivalId: 1,
  },
  {
    id: 2,
    authorName: '이재영',
    authorImage: '/mock/user2.png',
    date: '2025.07.31',
    likes: 10,
    content: '비가 와서 아쉽지만, 그래도 좋은 추억이었어요 ☔️',
    images: [],
    isPublic: true,
    festivalId: 2,
  },
  {
    id: 3,
    authorName: '박수연',
    authorImage: '/mock/user1.png',
    date: '2025.07.30',
    likes: 10,
    content: '속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊',
    images: [],
    isPublic: true,
    festivalId: 3,
  },
  {
    id: 4,
    authorName: '박수연',
    authorImage: '/mock/user1.png',
    date: '2025.08.03',
    likes: 10,
    content: '속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊 속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊 속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊 속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊 속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊 속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊',
    images: [],
    isPublic: true,
    festivalId: 3,
  },
  {
    id: 5,
    authorName: '박수연',
    authorImage: '/mock/user1.png',
    date: '2025.08.03',
    likes: 10,
    content: '속초 축제 다녀왔어요! 해변이 정말 예뻤어요 🌊',
    images: ['/images/test/review1.png', '/images/test/review2.png'],
    isPublic: true,
    festivalId: 3,
  },
];
